=== sultanmusin/pyslow/doc/na61-psd-slow-control/src/PsdSlowControlConfig.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="config">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="global">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="connection">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="hvsys">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="rate">
                            <xs:complexType>
                              <xs:simpleContent>
                                <xs:extension base="xs:int">
                                  <xs:attribute type="xs:string" name="unit"/>
                                </xs:extension>
                              </xs:simpleContent>
                            </xs:complexType>
                          </xs:element>
                          <xs:element type="xs:string" name="port"/>
                          <xs:element type="xs:byte" name="dataBits"/>
                          <xs:element type="xs:byte" name="stopBits"/>
                          <xs:element type="xs:byte" name="parity"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="tec">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="rate">
                            <xs:complexType>
                              <xs:simpleContent>
                                <xs:extension base="xs:int">
                                  <xs:attribute type="xs:string" name="unit"/>
                                </xs:extension>
                              </xs:simpleContent>
                            </xs:complexType>
                          </xs:element>
                          <xs:element type="xs:byte" name="dataBits"/>
                          <xs:element type="xs:byte" name="stopBits"/>
                          <xs:element type="xs:byte" name="parity"/>
                          <xs:element type="xs:float" name="firmware"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="settings">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="hv">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="base">
                            <xs:complexType>
                              <xs:simpleContent>
                                <xs:extension base="xs:float">
                                  <xs:attribute type="xs:string" name="unit"/>
                                </xs:extension>
                              </xs:simpleContent>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="module" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="geometry">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="size" minOccurs="1" maxOccurs="1">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:byte">
                            <xs:attribute type="xs:string" name="unit" use="optional"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="x" minOccurs="1" maxOccurs="1">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:short">
                            <xs:attribute type="xs:string" name="unit" use="optional"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="y" minOccurs="1" maxOccurs="1">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:short">
                            <xs:attribute type="xs:string" name="unit" use="optional"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="connection">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="hvsys">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="led">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element type="xs:byte" name="id" minOccurs="1" maxOccurs="1"/>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                          <xs:element name="hv" minOccurs="1" maxOccurs="1">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element type="xs:byte" name="id"/>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="tec">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element type="xs:string" name="port" minOccurs="1" maxOccurs="1"/>
                          <xs:element type="xs:byte" name="id" minOccurs="1" maxOccurs="1"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="settings">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="led" minOccurs="1" maxOccurs="1">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element type="xs:string" name="autoTune" minOccurs="1" maxOccurs="1"/>
                          <xs:element type="xs:short" name="brightness" minOccurs="1" maxOccurs="1"/>
                          <xs:element name="frequency" minOccurs="1" maxOccurs="1">
                            <xs:complexType>
                              <xs:simpleContent>
                                <xs:extension base="xs:byte">
                                  <xs:attribute type="xs:string" name="unit" use="optional"/>
                                </xs:extension>
                              </xs:simpleContent>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="hv" minOccurs="1" maxOccurs="1">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="channel" maxOccurs="10" minOccurs="10">
                            <xs:complexType>
                              <xs:simpleContent>
                                <xs:extension base="xs:float">
                                  <xs:attribute type="xs:byte" name="id" use="required"/>
                                  <xs:attribute type="xs:string" name="unit" use="optional"/>
                                </xs:extension>
                              </xs:simpleContent>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute type="xs:byte" name="id" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute type="xs:string" name="id"/>
      <xs:attribute type="xs:string" name="created"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== sultanmusin/pyslow/config/VETO.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<config xmlns="http://www.w3schools.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" created="17.02.2014" id="default" xsi:noNamespaceSchemaLocation="PsdSlowControlConfig.xsd" xsi:schemaLocation="PsdSlowControlConfig.xsd">
<global>
	<title>VETO DCS</title>
	<flags>
            <onlineModules> 1 </onlineModules>
            <queryDelay unit="sec">600</queryDelay>
            <verbose> 1 </verbose>
            <monitorHV> 0 </monitorHV>
            <refTemp> 25 </refTemp>
            <tempSlope> 60 </tempSlope>

        </flags>
        <connection>
            <hvsys id='05'>
                <rate unit="baud">57600</rate>
                <host>10.18.88.104</host>
                <port>4001</port>
                <dataBits>8</dataBits>
                <stopBits>1</stopBits>
                <parity>0</parity>                
            </hvsys>
        </connection>
        <settings>
            <hv>
                <base unit="Volts">64.0</base>
            </hv>
        </settings>
    </global>

    <module id="1" version="DM64_V2">
        <geometry>
            <size>1</size>
            <x>3</x>
            <y>4</y>
        </geometry>
                 
        <connection>
            <hvsys id='05'>
                <hv>
                    <id>1</id>
                </hv>
            </hvsys>
        </connection>    
        <settings>
            <hv>
                <channel id="1" unit="Volts">42.00</channel>
                <channel id="2" unit="Volts">42.00</channel>
                <channel id="3" unit="Volts">42.00</channel>
                <channel id="4" unit="Volts">42.00</channel>
                <channel id="5" unit="Volts">42.00</channel>
                <channel id="6" unit="Volts">42.00</channel>
                <channel id="7" unit="Volts">42.00</channel>
                <channel id="8" unit="Volts">42.00</channel>
                <channel id="9" unit="Volts">42.00</channel>
                <channel id="10" unit="Volts">42.00</channel>
                <channel id="11" unit="Volts">42.00</channel>
                <channel id="12" unit="Volts">42.00</channel>
                <channel id="13" unit="Volts">42.00</channel>
                <channel id="14" unit="Volts">42.00</channel>
                <channel id="15" unit="Volts">42.00</channel>
                <channel id="16" unit="Volts">42.00</channel>
                <pedestal unit="Volts">42.00</pedestal>
            </hv>
        </settings> 
        
    </module>
    <module id="2" version="DM64_V2">
        <geometry>
            <size>1</size>
            <x>3</x>
            <y>5</y>
        </geometry>
                 
        <connection>
            <hvsys id='05'>
                <hv>
                    <id>2</id>
                </hv>
            </hvsys>
        </connection>    
        <settings>
            <hv>
                <channel id="1" unit="Volts">42.00</channel>
                <channel id="2" unit="Volts">42.00</channel>
                <channel id="3" unit="Volts">42.00</channel>
                <channel id="4" unit="Volts">42.00</channel>
                <channel id="5" unit="Volts">42.00</channel>
                <channel id="6" unit="Volts">42.00</channel>
                <channel id="7" unit="Volts">42.00</channel>
                <channel id="8" unit="Volts">42.00</channel>
                <channel id="9" unit="Volts">42.00</channel>
                <channel id="10" unit="Volts">42.00</channel>
                <channel id="11" unit="Volts">42.00</channel>
                <channel id="12" unit="Volts">42.00</channel>
                <channel id="13" unit="Volts">42.00</channel>
                <channel id="14" unit="Volts">42.00</channel>
                <channel id="15" unit="Volts">42.00</channel>
                <channel id="16" unit="Volts">42.00</channel>
                <pedestal unit="Volts">42.00</pedestal>
            </hv>
        </settings> 
    </module>
</config>

=== sultanmusin/pyslow/config/FPSD.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<config xmlns="http://www.w3schools.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" created="17.02.2014" id="default" xsi:noNamespaceSchemaLocation="PsdSlowControlConfig.xsd" xsi:schemaLocation="PsdSlowControlConfig.xsd">
<global>
        <flags>
<onlineModules>1</onlineModules>
<onlineModules>2</onlineModules>
<onlineModules>3</onlineModules>
<onlineModules>4</onlineModules>
<onlineModules>5</onlineModules>
<onlineModules>6</onlineModules>
<onlineModules>7</onlineModules>
<onlineModules>8</onlineModules>
<onlineModules>9</onlineModules>

            <queryDelay unit="sec">600</queryDelay>
            <verbose> 1 </verbose>
            <useVoiceNotifications> 0 </useVoiceNotifications>
            <voiceServer> na61daqt </voiceServer>
            <monitorHV> 0 </monitorHV>
            <refTemp> 25 </refTemp>
            <tempSlope> 60 </tempSlope>

        </flags>
        <connection>
		<hvsys>
		        <rate unit="baud">57600</rate>
                        <port>10.0.9.3</port>
		        <dataBits>8</dataBits>
		        <stopBits>1</stopBits>
		        <parity>0</parity>		        
		</hvsys>
		</connection>
		<settings>
		    <hv>
		        <base unit="Volts">64.0</base>
		    </hv>
		</settings>
    </global>
    
<module id="1">
    	<geometry>
    	    <size>1</size>
    	    <x>8</x>
            <y>4</y>
    	</geometry>
    	    	 
    	<connection>
			<hvsys>
				<hv>
				    <id>1</id>
				</hv>
			</hvsys>
    	        	</connection>    
    	<settings>
			<hv>
                <channel id="1" unit="Volts">50</channel>
				<channel id="2" unit="Volts">69.89</channel>
				<channel id="3" unit="Volts">69.89</channel>
				<channel id="4" unit="Volts">69.89</channel>
				<channel id="5" unit="Volts">69.89</channel>
				<channel id="6" unit="Volts">69.89</channel>
				<channel id="7" unit="Volts">69.89</channel>
				<channel id="8" unit="Volts">69.89</channel>
				<channel id="9" unit="Volts">69.89</channel>
				<channel id="10" unit="Volts">69.89</channel>
                <pedestal unit="Volts">69.89</pedestal>
			</hv>
    	</settings> 
    	
    </module>
<module id="2">
    	<geometry>
    	    <size>1</size>
    	    <x>7</x>
    	   	<y>4</y>
    	</geometry>
    	    	 
    	<connection>
			<hvsys>
				<hv>
				    <id>2</id>
				</hv>
			</hvsys>
    	        	</connection>    
    	<settings>
			<hv>
				<channel id="1" unit="Volts">69.91</channel>
				<channel id="2" unit="Volts">69.91</channel>
				<channel id="3" unit="Volts">69.91</channel>
				<channel id="4" unit="Volts">69.91</channel>
				<channel id="5" unit="Volts">69.91</channel>
				<channel id="6" unit="Volts">69.91</channel>
				<channel id="7" unit="Volts">69.91</channel>
				<channel id="8" unit="Volts">69.91</channel>
				<channel id="9" unit="Volts">69.91</channel>
				<channel id="10" unit="Volts">69.91</channel>
                                <pedestal unit="Volts">69.91</pedestal>
			</hv>
    	</settings> 
    	
    </module>
<module id="3">
    	<geometry>
    	    <size>1</size>
    	    <x>6</x>
    	   	<y>4</y>
    	</geometry>
    	    	 
    	<connection>
			<hvsys>
				<hv>
				    <id>3</id>
				</hv>
			</hvsys>
    	        	</connection>    
    	<settings>
			<hv>
				<channel id="1" unit="Volts">71.07</channel>
				<channel id="2" unit="Volts">71.07</channel>
				<channel id="3" unit="Volts">71.07</channel>
				<channel id="4" unit="Volts">71.07</channel>
				<channel id="5" unit="Volts">71.07</channel>
				<channel id="6" unit="Volts">71.07</channel>
				<channel id="7" unit="Volts">71.07</channel>
				<channel id="8" unit="Volts">71.07</channel>
				<channel id="9" unit="Volts">71.07</channel>
				<channel id="10" unit="Volts">71.07</channel> 
                                <pedestal unit="Volts">71.07</pedestal>
			</hv>
    	</settings> 
    	
    </module>
<module id="4">
    	<geometry>
    	    <size>1</size>
    	    <x>8</x>
    	   	<y>5</y>
    	</geometry>
    	    	 
    	<connection>
			<hvsys>
				<hv>
				    <id>4</id>
				</hv>
			</hvsys>
    	        	</connection>    
    	<settings>
			<hv>
				<channel id="1" unit="Volts">69.99</channel>
				<channel id="2" unit="Volts">69.99</channel>
				<channel id="3" unit="Volts">69.99</channel>
				<channel id="4" unit="Volts">69.99</channel>
				<channel id="5" unit="Volts">69.99</channel>
				<channel id="6" unit="Volts">69.99</channel>
				<channel id="7" unit="Volts">69.99</channel>
				<channel id="8" unit="Volts">69.99</channel>
				<channel id="9" unit="Volts">69.99</channel>
				<channel id="10" unit="Volts">69.99</channel> 
                                <pedestal unit="Volts">69.99</pedestal>
			</hv>
    	</settings> 
    	
    </module>
<module id="5">
    	<geometry>
    	    <size>1</size>
    	    <x>7</x>
    	   	<y>5</y>
    	</geometry>
    	    	 
    	<connection>
			<hvsys>
				<hv>
				    <id>5</id>
				</hv>
			</hvsys>
    	        	</connection>    
    	<settings>
			<hv>
				<channel id="1" unit="Volts">69.99</channel>
				<channel id="2" unit="Volts">69.99</channel>
				<channel id="3" unit="Volts">69.99</channel>
				<channel id="4" unit="Volts">69.99</channel>
				<channel id="5" unit="Volts">69.99</channel>
				<channel id="6" unit="Volts">69.99</channel>
				<channel id="7" unit="Volts">69.99</channel>
				<channel id="8" unit="Volts">69.99</channel>
				<channel id="9" unit="Volts">69.99</channel>
				<channel id="10" unit="Volts">69.99</channel> 
                                <pedestal unit="Volts">69.99</pedestal>
			</hv>
    	</settings> 
    	
    </module>
<module id="6">
    	<geometry>
    	    <size>1</size>
    	    <x>6</x>
    	   	<y>5</y>
    	</geometry>
    	    	 
    	<connection>
			<hvsys>
				<hv>
				    <id>6</id>
				</hv>
			</hvsys>
    	        	</connection>    
    	<settings>
			<hv>
				<channel id="1" unit="Volts">69.94</channel>
				<channel id="2" unit="Volts">69.94</channel>
				<channel id="3" unit="Volts">69.94</channel>
				<channel id="4" unit="Volts">69.94</channel>
				<channel id="5" unit="Volts">69.94</channel>
				<channel id="6" unit="Volts">69.94</channel>
				<channel id="7" unit="Volts">69.94</channel>
				<channel id="8" unit="Volts">69.94</channel>
				<channel id="9" unit="Volts">69.94</channel>
				<channel id="10" unit="Volts">69.94</channel> 
                                <pedestal unit="Volts">69.94</pedestal>
			</hv>
    	</settings> 
    	
    </module>
<module id="7">
    	<geometry>
    	    <size>1</size>
    	    <x>8</x>
    	   	<y>6</y>
    	</geometry>
    	    	 
    	<connection>
			<hvsys>
				<hv>
				    <id>7</id>
				</hv>
			</hvsys>
    	        	</connection>    
    	<settings>
			<hv>
				<channel id="1" unit="Volts">71.10</channel>
				<channel id="2" unit="Volts">71.10</channel>
				<channel id="3" unit="Volts">71.10</channel>
				<channel id="4" unit="Volts">71.10</channel>
				<channel id="5" unit="Volts">71.10</channel>
				<channel id="6" unit="Volts">71.10</channel>
				<channel id="7" unit="Volts">71.10</channel>
				<channel id="8" unit="Volts">71.10</channel>
				<channel id="9" unit="Volts">71.10</channel>
				<channel id="10" unit="Volts">71.10</channel> 
                                <pedestal unit="Volts">71.10</pedestal>
			</hv>
    	</settings> 
    	
    </module>
<module id="8">
    	<geometry>
    	    <size>1</size>
    	    <x>7</x>
    	   	<y>6</y>
    	</geometry>
    	    	 
    	<connection>
			<hvsys>
				<hv>
				    <id>8</id>
				</hv>
			</hvsys>
    	        	</connection>    
    	<settings>
			<hv>
				<channel id="1" unit="Volts">71.15</channel>
				<channel id="2" unit="Volts">71.15</channel>
				<channel id="3" unit="Volts">71.15</channel>
				<channel id="4" unit="Volts">71.15</channel>
				<channel id="5" unit="Volts">71.15</channel>
				<channel id="6" unit="Volts">71.15</channel>
				<channel id="7" unit="Volts">71.15</channel>
				<channel id="8" unit="Volts">71.15</channel>
				<channel id="9" unit="Volts">71.15</channel>
				<channel id="10" unit="Volts">71.15</channel> 
                                <pedestal unit="Volts">71.15</pedestal>
			</hv>
    	</settings> 
    	
    </module>
<module id="9">
    	<geometry>
    	    <size>1</size>
    	    <x>6</x>
    	   	<y>6</y>
    	</geometry>
    	    	 
    	<connection>
			<hvsys>
				<hv>
				    <id>9</id>
				</hv>
			</hvsys>
    	        	</connection>    
    	<settings>
			<hv>
				<channel id="1" unit="Volts">71.03</channel>
				<channel id="2" unit="Volts">71.03</channel>
				<channel id="3" unit="Volts">71.03</channel>
				<channel id="4" unit="Volts">71.03</channel>
				<channel id="5" unit="Volts">71.03</channel>
				<channel id="6" unit="Volts">71.03</channel>
				<channel id="7" unit="Volts">71.03</channel>
				<channel id="8" unit="Volts">71.03</channel>
				<channel id="9" unit="Volts">71.03</channel>
				<channel id="10" unit="Volts">71.03</channel> 
                                <pedestal unit="Volts">71.03</pedestal>
			</hv>
    	</settings> 
    </module>
</config>

=== sultanmusin/pyslow/config/hodo.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<config xmlns="http://www.w3schools.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" created="17.02.2014" id="default" xsi:noNamespaceSchemaLocation="PsdSlowControlConfig.xsd" xsi:schemaLocation="PsdSlowControlConfig.xsd">
<global>
	<title>hodo DCS</title>
	<flags>
            <onlineModules> 141,142,143,144 </onlineModules>

            <queryDelay unit="sec">600</queryDelay>
            <verbose> 1 </verbose>
            <monitorHV> 0 </monitorHV>
            <refTemp> 25 </refTemp>
            <tempSlope> 60 </tempSlope>

        </flags>
        <connection>
        <hvsys id="fhcal">
                <rate unit="baud">57600</rate>
                <port>10.18.88.134</port>
                <dataBits>8</dataBits>
                <stopBits>1</stopBits>
                <parity>0</parity>                
        </hvsys>
        </connection>
        <settings>
            <hv>
                <base unit="Volts">64.0</base>
            </hv>
        </settings>
    </global>

    <module id="141">
        <geometry>
            <size>1</size>
            <x>1</x>
            <y>7</y>
        </geometry>
                 
        <connection>
            <hvsys id="fhcal">
                <hv>
                    <id>141</id>
                </hv>
            </hvsys>
        </connection>    
        <settings>
            <hv>
                <channel id="1" unit="Volts">42.0</channel>
                <channel id="2" unit="Volts">42.0</channel>
                <channel id="3" unit="Volts">42.0</channel>
                <channel id="4" unit="Volts">42.0</channel>
                <channel id="5" unit="Volts">42.0</channel>
                <channel id="6" unit="Volts">42.0</channel>
                <channel id="7" unit="Volts">42.0</channel>
                <channel id="8" unit="Volts">42.0</channel>
                <pedestal unit="Volts">42.0</pedestal>
            </hv>
        </settings> 
        
    </module>

    <module id="142" temperature_from_module="141">
        <geometry>
            <size>1</size>
            <x>2</x>
            <y>7</y>
        </geometry>
                 
        <connection>
            <hvsys id="fhcal">
                <hv>
                    <id>142</id>
                </hv>
            </hvsys>
        </connection>    
        <settings>
            <hv>
                <channel id="1" unit="Volts">42.0</channel>
                <channel id="2" unit="Volts">42.0</channel>
                <channel id="3" unit="Volts">42.0</channel>
                <channel id="4" unit="Volts">42.0</channel>
                <channel id="5" unit="Volts">42.0</channel>
                <channel id="6" unit="Volts">42.0</channel>
                <channel id="7" unit="Volts">42.0</channel>
                <channel id="8" unit="Volts">42.0</channel>
                <pedestal unit="Volts">42.0</pedestal>
            </hv>
        </settings> 
        
    </module>

    <module id="143" temperature_from_module="141">
        <geometry>
            <size>1</size>
            <x>3</x>
            <y>7</y>
        </geometry>
                 
        <connection>
            <hvsys id="fhcal">
                <hv>
                    <id>143</id>
                </hv>
            </hvsys>
        </connection>    
        <settings>
            <hv>
                <channel id="1" unit="Volts">42.0</channel>
                <channel id="2" unit="Volts">42.0</channel>
                <channel id="3" unit="Volts">42.0</channel>
                <channel id="4" unit="Volts">42.0</channel>
                <channel id="5" unit="Volts">42.0</channel>
                <channel id="6" unit="Volts">42.0</channel>
                <channel id="7" unit="Volts">42.0</channel>
                <channel id="8" unit="Volts">42.0</channel>
                <pedestal unit="Volts">42.0</pedestal>
            </hv>
        </settings> 
        
    </module>

    <module id="144" temperature_from_module="144">
        <geometry>
            <size>1</size>
            <x>4</x>
            <y>7</y>
        </geometry>
                 
        <connection>
            <hvsys id="fhcal">
                <hv>
                    <id>144</id>
                </hv>
            </hvsys>
        </connection>    
        <settings>
            <hv>
                <channel id="1" unit="Volts">42.0</channel>
                <channel id="2" unit="Volts">42.0</channel>
                <channel id="3" unit="Volts">42.0</channel>
                <channel id="4" unit="Volts">42.0</channel>
                <channel id="5" unit="Volts">42.0</channel>
                <channel id="6" unit="Volts">42.0</channel>
                <channel id="7" unit="Volts">42.0</channel>
                <channel id="8" unit="Volts">42.0</channel>
                <pedestal unit="Volts">42.0</pedestal>
            </hv>
        </settings> 
        
    </module>


</config>
